### PR TITLE
v0.1.0.2: Support Cabal-3.12 (GHC 9.10)

### LINKED ISSUE #73: Support Cabal 3.12
```
lib/Distribution/Server/Util/CabalRevisions.hs:181:21: error: [GHC-83865]
    • Couldn't match expected type: Maybe a1 -> [PackageCheck]
                  with actual type: [PackageCheck]
    • The function ‘checkPackage’ is applied to two visible arguments,
        but its type ‘GenericPackageDescription -> [PackageCheck]’
        has only one
      In the expression: checkPackage pkg Nothing
      In an equation for ‘checks’: checks = checkPackage pkg Nothing
    |
181 |       let checks  = checkPackage pkg  Nothing
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by andreasabel**
https://hackage.haskell.org/package/hackage-cli-0.1.0.2/candidate

### CODE REVIEW

**Comment by andreasabel** [comment]
Stack build with GHC 9.10 broken:
- https://github.com/haskell-cryptography/HsOpenSSL/issues/92
